# Generated by Django 5.0.4 on 2024-05-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField()),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("height", models.CharField(max_length=10)),
                ("weight", models.IntegerField()),
                ("jersey_number", models.IntegerField()),
                ("college", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("draft_year", models.IntegerField()),
                ("draft_round", models.IntegerField()),
                ("draft_number", models.IntegerField()),
                ("team", models.CharField(max_length=100)),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Past_Searches",
        ),
    ]
