# Generated by Django 5.0.4 on 2024-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_playersearchhistory_delete_past_searches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playersearchhistory",
            name="draft_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playersearchhistory",
            name="draft_round",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playersearchhistory",
            name="draft_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
